### ISSUE TITLE
Domain Issue

### ISSUE THREAD

**Issue by PrakashRavichandrann** [msanvarov/personal-portfolio#317]
When I link the portfolio GitHub repo and Godaddy domain, It does not work. How can I solve it Mr. @msanvarov ?

[https://github.com/PrakashRavichandrann/personal-portfolio](https://github.com/PrakashRavichandrann/personal-portfolio)

**Comment by msanvarov** [comment]
Hey @PrakashRavichandrann, what are you currently trying to do?

**Comment by PrakasRavichandran** [comment]
@msanvarov Are you there ?

**Comment by msanvarov** [comment]
Yes I am, why don't you book me for a 30 min chat. I can help fix your problem https://calendly.com/msalanvarov
